name = "btc_parser"
version = "1.0.0"

description = "Decode and inspect Bitcoin wire-format data structures."
licences = ["MIT"]

[repository]
type = "github"
user = "caquinn7"
repo = "btc-parser"

gleam = ">= 1.16.0"

target = "erlang"
internal_modules = ["btc_parser/internal/*"]

[javascript]
runtime = "node"
source_maps = true

[javascript.deno]
allow_read = true
allow_write = true

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
exception = ">= 2.1.0 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
gleamy_bench = ">= 0.6.0 and < 1.0.0"
