name = "btc_parser_fuzz"
version = "1.0.0"

gleam = ">= 1.16.0"

target = "erlang"
internal_modules = ["btc_parser_fuzz/internal/*"]

[javascript]
runtime = "node"
source_maps = true

[javascript.deno]
allow_read = true

[dependencies]
btc_parser = { path = ".." }
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
exception = ">= 2.1.0 and < 3.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
