name: fuzz

on:
  push:
    branches:
      - main

jobs:
  seed:
    runs-on: ubuntu-latest

    outputs:
      seed: ${{ steps.generate.outputs.seed }}

    steps:
      - name: Generate seed
        id: generate
        run: echo "seed=$(od -An -N4 -tu4 < /dev/urandom | tr -d ' \n')" >> "$GITHUB_OUTPUT"

  fuzz:
    runs-on: ubuntu-latest
    needs: [seed]

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: erlang
          - target: javascript
            js_runtime: node
          - target: javascript
            js_runtime: deno
          - target: javascript
            js_runtime: bun

    steps:
      - uses: actions/checkout@v4

      - name: Setup runtimes
        uses: ./.github/actions/setup
        with:
          js_runtime: ${{ matrix.js_runtime }}

      - name: Run fuzz tests
        timeout-minutes: 5
        run: |
          gleam deps download
          if [ "${{ matrix.target }}" = "javascript" ]; then
            gleam dev --target javascript --runtime ${{ matrix.js_runtime }} fuzz 100000 ${{ needs.seed.outputs.seed }}
          else
            gleam dev --target erlang fuzz 100000 ${{ needs.seed.outputs.seed }}
          fi
