name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup runtimes
        uses: ./.github/actions/setup

      - name: Check formatting
        run: gleam format --check

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: erlang
          - target: javascript
            js_runtime: node
          - target: javascript
            js_runtime: deno
          - target: javascript
            js_runtime: bun

    steps:
      - uses: actions/checkout@v4

      - name: Setup runtimes
        uses: ./.github/actions/setup
        with:
          js_runtime: ${{ matrix.js_runtime }}

      - name: Run tests
        run: |
          gleam deps download
          if [ "${{ matrix.target }}" = "javascript" ]; then
            gleam test --target javascript --runtime ${{ matrix.js_runtime }}
          else
            gleam test --target erlang
          fi
